### ISSUE TITLE
iPad Viewer Crashes - iOS8

### ISSUE THREAD

**Issue by keithwahn** [fpillet/NSLogger#156]
Target: iPad Air (8.3) simulator

After the app establishes a connection to the client, it crashes at:

**LoggerMessageCell.m , Line 68**
```
2015-04-14 12:33:58.785 iPad Viewer[45465:16332642] -[UITableViewWrapperView drawMessageView:]: unrecognized selector sent to instance 0x7ffd2b6ba8a0
```

**Comment by stkim1** [comment]
@keithwahn I'm looking into it. Sorry for the delay.

**Comment by stkim1** [comment]
UI is going to be reconstructed. Just very basic crash issues are removed at this point. Stay tuned.

**Comment by stkim1** [comment]
iPad Viewer now support iOS version 9.x without crashes.
