### ISSUE TITLE
Offer viewer apps for purchase through app stores

### ISSUE THREAD

**Issue by kellytk** [fpillet/NSLogger#161]
NSLogger is useful to me and I appreciate the work that's gone into it.  Please consider offering the viewer apps through Apple's app stores.  I would pay for them for the convenience and to support the developer.

**Comment by fpillet** [comment]
Thank you, Kelly. This has been considered, right now I didn't do it mostly because of the sandboxing requirements for the AppStore.

Glad you enjoy NSLogger! Means a lot to me 👍
