### ISSUE TITLE
Saving logs to external files in a desktop viewer format

### ISSUE THREAD

**Issue by Saurman** [fpillet/NSLogger#163]
Hello, thanks for a nice library. Would be nice to see/save/email all logs as files than was not transmitted to desktop viewer

**Comment by Saurman** [comment]
Any news on this one?

**Comment by fpillet** [comment]
I'm not sure what your expectations are exactly. You didn't provide information about exactly what you want to achieve. Please clarify.

**Comment by Saurman** [comment]
Sorry, desktop viewer allows me to export logs into files that can be imported later back to a desktop viewer. 

I have NSLogger built-in to my app and id users to be able to mail me log files without having desktop client running all the time. In other words i expect NSLogger to have an option, when enable will save logs to a file of a format that desktop viewer can read.

**Comment by fpillet** [comment]
Client logger has options to write to a binary file, which you can open on the desktop (provided you name it with a ".nsloggerdata" extension). If you manage to transport this file to your desktop, you can open it right away with NSLogger desktop.

**Comment by Saurman** [comment]
Can u explain what methods have to be used to achieve this? I cannot find this info in wiki. Sample app would be perfect

**Comment by fpillet** [comment]
Look in `LoggerClient.h`, you want to use the `LoggerSetBufferFile()` and pass it the path you want to save the log file to. Uploading the resulting log file is your app's responsibility, NSLogger won't do it for you.

**Comment by Saurman** [comment]
I've tried this method, it produces incompatible format. Desktop viewer cannot open it. nsloggerdata files exported from desktop viewer look like XML while LoggerSetBufferFile creates binary file

**Comment by fpillet** [comment]
Ouch ok this was supposed to be working .. guess I need to look into this but I'm too short on time right now.
