### ISSUE TITLE
[Question] Why enable custom logs colors only in `Debug` mode ? (Not in `Release`)

### ISSUE THREAD

**Issue by rvi** [fpillet/NSLogger#168]
As we can see [here](https://github.com/fpillet/NSLogger/blob/master/Desktop%20Viewer/Classes/LoggerMessageCell.m#L350-L354),  you add the color by looking for a regex on `[loggerMessage description]` : 

```Objc
+ (NSColor *)colorForMessage:(LoggerMessage *)message
{
    /* `description` is supposed to be used just for debugging...exactly the main purpose of NSLogger */
    return [self colorForString:[message description]];
}
```

But in LoggerMessage.m, `description` is override only if we're compiling in `Debug` : 

```Objc
#ifdef DEBUG
-(NSString *)description
{
     // Build the description of LoggerMessage
}
#endif
```

Why are you doing this?  is it normal?

If I have not misunderstood, `[loggerMessage description]` will be something like that : `<LoggerMessage : 0x123456>` in `Release` mode.

If needed, I can submit a pull request if you want. 

Thanks for this great tool.

Cheers.

**Comment by tifroz** [comment]
+1 would love to see coloring working

**Comment by rvi** [comment]
@tifroz I fixed it. 

You can clone my fork and build the desktop client.

Here it is : https://github.com/rvi/NSLogger

**Comment by fpillet** [comment]
Since I often run NSLogger in debug mode I didn't notice this :) thanks for the fix, I'll push it to the main repo before making a new release!
