### ISSUE TITLE
EXC_GUARD during LoggerStop()

### ISSUE THREAD

**Issue by andrewbradnan** [fpillet/NSLogger#170]
Ever seen an EXC_GUARD exception being thrown during LoggerStopConsoleRedirection()?  It dies on dup2 for stderr.  Strange that it works on the previous line for stdout.

Every so often I reset the file I log back to empty.  Hence the call to LoggerStop().

Oh yeah, it works 99% of the time....just to make it maddening.

Any clue?

**Comment by andrewbradnan** [comment]
Oh, i c.  You never set sSTDOUT/sSTDERR back to it's initial state of -1, so it never dups the handle the second time through LoggerStartConsoleRedirection().

I wonder how it ever works....

**Comment by fpillet** [comment]
Ha! Good catch. It works because 99.9% users don't ever call LoggerStop(). Want to submit a pull request?

**Comment by andrewbradnan** [comment]
Yeah sure, will do a pull request...
