### ISSUE TITLE
Unable to open logs in desktop viewer

### ISSUE THREAD

**Issue by aschearer** [fpillet/NSLogger#172]
Tried the latest release and also building from the latest in master. Hitting exceptions in LoggerNativeMessage.initWithData. Line 48 seems to be the culprit.

**Comment by Tilium** [comment]
I'm too! I can't open no one logs from my clients on desktop app. Please help us

**Comment by Tilium** [comment]
I resolve problem. I try to send log files vie MFMailComposeViewController with mime-type 'text/plain', but email app convert binary log-file and in result damage it, when I pack log-file to zip-archive and select mime-type 'application/zip' I can get correct files on my email.

**Comment by fpillet** [comment]
Good! Thanks for letting me know.
