### ISSUE TITLE
Crashes on El Capitan

### ISSUE THREAD

**Issue by polynatic** [fpillet/NSLogger#176]
Hi, we're using NSLogger on a couple of development machines and since the El Capitan update NSLogger has become quite instable. It is crashing on various and unpredictable occasions. I didn't have time to look into the issue myself, so my question is: Is there anybody looking after that?

**Comment by fpillet** [comment]
At the time I'm still developing on Yosemite, but yes I have received reports of high instability on El Capitan. I'm lacking time, like you, so I'll check this out as soon as possible but if you have some time to track the issues, a PR would be appreciated :)

**Comment by fpillet** [comment]
Fixed a bunch of the issues in master, will make a binary release ASAP
