### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by victorgama** [fpillet/NSLogger#182]
This library is perfect, but I was wondering if you do plan supporting Carthage in the near future.
Thanks!

**Comment by stkim1** [comment]
@victorgama You know, these days, `Pull Request` is way of showing your love and paying respect. It would be awesome if you can write a PR for [Carthage](https://github.com/Carthage/Carthage). 

Don't you want to put your name on the [contributors](https://github.com/fpillet/NSLogger/graphs/contributors)? :sunglasses:

**Comment by victorgama** [comment]
@stkim1 Fair enough. 
I've been looking into that, and there's some points I'd like to expose before opening a PR. 
The first one, is that I will need to create an `xcodeproj` for NSLogger. (I don't think this will be a problem for you guys.)
The second, is that I will need to rename `Desktop Viewer/NSLogger.xcodeproj` to `Desktop Viewer/NSLoggerViewer.xcodeproj`. Would you mind? Carthage gets a little confused which `xcodeproj` to build and this may result in failures. (My major concern)
