### ISSUE TITLE
NSLogger Desktop app for Windows?

### ISSUE THREAD

**Issue by AmitWix** [fpillet/NSLogger#185]
Hi There, 
I have just integrated NSLogger to our iOS app and it seems to work fabulously!
However, we also have an Android app, and I saw that you have a solution for Android as well. 
The problem is that our Android developers usually work with windows desktops.
Do you have any plans for porting the NSLogger desktop application to windows? 

Thanks!
Amit.

**Comment by fpillet** [comment]
Nope, sorry.

**Comment by bukira** [comment]
can anyome make for windows?
