### ISSUE TITLE
Disabling networking

### ISSUE THREAD

**Issue by cssbz** [fpillet/NSLogger#190]
I'm happily using NSLogger to debug the test version of my Mac app (10.11+).  It's a great tool - thank you!

But in the release version of my app, I've disabled networking in the sandbox (I haven't included `com.apple.security.network.client`), as the app doesn't need it.

Instead, I'm logging to a file, and if there is an issue, I'm planning to ask the customer to email the file to me.

There's a minor issue, though.  I see the following in the console at app launch:

    04/03/2016 22:00:22.000 kernel[0]: Sandbox: Spendid(10848) deny(1) mach-lookup com.apple.networkd
    04/03/2016 22:00:22.521 Spendid[10848]: __nw_path_evaluator_start_helper_connection_block_invoke net_helper_path_evaluation_start callback failed, dumping backtrace:
    ...

This seems to be caused by `LoggerStartReachabilityChecking`.  I can avoid the error by commenting out that function, and I might do that in my release version.

Have I missed something, though?   I was assuming from the docs that if `kLoggerOption_BrowseBonjour` was 0, then networking would be disabled, unless I called `LoggerSetViewerHost`.

So, if I understand correctly, perhaps `LoggerStartReachabilityChecking` should only operate `if ((logger->options & kLoggerOption_BrowseBonjour) || (logger->host != NULL))` (although untested and I'm not particularly confident of that...).  Or would a new `kLoggerOption_EnableNetworking` be a good idea?

**Comment by fpillet** [comment]
You are absolutely right, Reachability should be used only when networking is being required. If you are only logging locally, then checking for reachability is totally superfluous. I'll fix this.

**Comment by cssbz** [comment]
Great!  Many thanks.
