### ISSUE TITLE
The desktop viewer doesn't open on OSX 10.11.4

### ISSUE THREAD

**Issue by kishykumar** [fpillet/NSLogger#200]
I downloaded NSLogger 1.6.0 prebuilt on OSX ElCapitan 10.11.4. 

When I click on NSLogger app, the app icon shows on the Dock, but no window/viewer is shown. It looks like it crashed, but the icon still appears on the Dock. 

Help is appreciated.

**Comment by nkanellopoulos** [comment]
A window will open automatically as soon as an application logs messages. It can be confusing, but this is the normal behaviour.

**Comment by AwayQu** [comment]
amazing design0.0
