### ISSUE TITLE
Slow logging

### ISSUE THREAD

**Issue by Michal1313** [fpillet/NSLogger#202]
Hi,

I started to using NSLogger with swift. My problem is that NSLogger log with 1-2 seconds delay. Here is my NSLogger initialisation code:

`       

```
    let logger = LoggerInit()

    let options:UInt32 = UInt32(kLoggerOption_LogToConsole | kLoggerOption_BrowseBonjour)

    LoggerSetOptions(logger, options)

    LoggerStart(logger)
```

`

is there any way to speed up loging?

**Comment by fpillet** [comment]
Why are you logging to console at all? Just disable the `kLoggerOption_LogToConsole` flag. There's no reason your logging is being delayed. I assume you're on wifi?

**Comment by Michal1313** [comment]
Well WiFi is enabled, but logs are delayed during app debuging, while device is connected to macbook via USB cable. The reason why I enabled logging to console is that I wanted to check if logs will be delayed as well. After doing that I noticed that console logs are delayed for the same amount of time like browser logs.

**Comment by fpillet** [comment]
Is it a problem you're still having?
