### ISSUE TITLE
NSLogger Desktop viewer does not honor port number specified in preferences

### ISSUE THREAD

**Issue by c0diq** [fpillet/NSLogger#206]
On El Capitan, specifying a port number is not honored. Opening Bonjour Browser app shows that NSLogger still chooses a random port.

**Comment by faken** [comment]
+1 - also having this issue!

**Comment by MonsieurDart** [comment]
The TCP port that we can define in the pref pane is not used for Bonjour, but only for "plain TCP". To see more about the open ports, you can go to the menu item "Window > Show Logger Status" and you will see which ports are used.

To force using a fixed port and host using this:

        LoggerSetViewerHost(nil, "localhost" as NSString, 50000)

**Comment by fpillet** [comment]
As @MonsieurDart puts it, Bonjour currently automatically picks a random port. Is there any specific usage scenario where this feature would be useful?
