### ISSUE TITLE
Network and console logging at the same time

### ISSUE THREAD

**Issue by mlostekk** [fpillet/NSLogger#208]
Is there some way to set up the NSLogger to log to console and to network at the same time?

**Comment by fpillet** [comment]
Just realized I never answered your question.

Use `LoggerSetOptions(NULL, (LoggerGetOptions(NULL) & ~kLoggerOption_CaptureSystemConsole) | kLoggerOption_LogToConsole)`

This will stop capturing the OS console output and log everything there too instead
