### ISSUE TITLE
LoggerClient.m: runtime: Threading Issues: Data race in LoggerPushMessageToQueue

### ISSUE THREAD

**Issue by JayZhao** [fpillet/NSLogger#210]
<img width="1204" alt="screen shot 2016-09-15 at 5 05 18 pm" src="https://cloud.githubusercontent.com/assets/2278174/18544375/da7b6af2-7b66-11e6-9134-9a72e125bee7.png">

Just use Xcode 8 to reproduce this warning.

**Comment by fpillet** [comment]
Thanks that's interesting. I'm looking into it.

**Comment by nenadvulic** [comment]
+1

**Comment by fpillet** [comment]
Fixed for 1.8.0, thanks!
