### ISSUE TITLE
Log Message is not displayed immediately in Console

### ISSUE THREAD

**Issue by Tibbs** [fpillet/NSLogger#211]
When I put a breakpoint after a log message it does not display it immediately in the NSLogger viewer. 
Sometimes have to step over a few lines to make the messages show up, but sometimes It only works when I press run. I'm using default config, running iOS 10 simulator and I tried both 1.7.0 and the latest commit.

**Comment by fpillet** [comment]
This is not a bug, it's a feature. NSLogger does send the logs from a secondary thread to avoid slowing down your code.

If you want logs to be sent before the code goes to the next line, you can use the `LoggerFlush(NULL, true)` function in your log macros. This effectively blocks until the log has bee n dispatched to the desktop viewer.

**Comment by Tibbs** [comment]
That makes sense, thank you very much for the quick answer!
