### ISSUE TITLE
File name and function name is empty in viewer.

### ISSUE THREAD

**Issue by cjskw** [fpillet/NSLogger#215]
I test with `LoggerError(0, @"some error message");` and the message content is correct but file name and function name is empty in viewer (OSX 10.11, last release of NSLogger).

![image](https://cloud.githubusercontent.com/assets/21332141/21041476/27ede1a0-be26-11e6-9b7d-be6a89e3b6c3.png)

**Comment by fpillet** [comment]
That's correct, this information is not currently being displayed in the textual version (mostly for readability purposes)
