### ISSUE TITLE
Podfile doesn't install NSLogger.swift

### ISSUE THREAD

**Issue by bcattle** [fpillet/NSLogger#220]
Hey,
Let me know if I'm missing something, but after installing NSLogger with Cocoapods, the ObjC files are present in the project but not the Swift file: 

<img width="235" alt="screen shot 2017-03-30 at 2 56 42 pm" src="https://cloud.githubusercontent.com/assets/620058/24527975/58df2b54-1559-11e7-9c72-ee33a327e9a3.png">

I tried adding both 

    pod 'NSLogger'

and 

    pod 'NSLogger/Standard'

to my `Podfile`. Is there some additional step required? Thanks.

**Comment by fpillet** [comment]
NSLogger 1.8.0 (which supports Swift) has not been released yet. It will happen very soon, waiting for it you can point to the HEAD of the repo to get NSLogger.swift installed:

```
pod 'NSLogger', :git => 'https://github.com/fpillet/NSLogger.git', :commit => 'HEAD'
```
