### ISSUE TITLE
function: LoggerWorkerThread leaks

### ISSUE THREAD

**Issue by volodg** [fpillet/NSLogger#224]
This code cause a leak inside of calling "CFRunLoopRunInMode"
```
	while (!logger->quit)
	{
		int result = CFRunLoopRunInMode(kCFRunLoopDefaultMode, timeout, true);
		if (result == kCFRunLoopRunFinished || result == kCFRunLoopRunStopped)
			break;
		if (result == kCFRunLoopRunHandledSource)
		{
			timeout = 0.0;
			continue;
		}
		timeout = fmax(1.0, fmin(0.10, timeout+0.0005));
	}
```

<img width="1407" alt="screen shot 2017-05-08 at 3 51 08 pm" src="https://cloud.githubusercontent.com/assets/32120/25796530/646ce9bc-340c-11e7-8de3-5084ae14b4d2.png">

**Comment by fpillet** [comment]
I tried to replicate this issue but couldn't ... also, this very much looks like a false positive, there's not much we can do here!
