### ISSUE TITLE
CFNetwork SSLHandshake failed (-9806)

### ISSUE THREAD

**Issue by ytx0574** [fpillet/NSLogger#227]
I remember before in 10.12 it is normal, and then to 10.13 Beta shows this error, the desktop client unable to display the log content

**Comment by ytx0574** [comment]
this the desktop client log:

setupSSLForStream, stream=<__NSCFInputStream: 0x6080001068a0> self=<LoggerNativeTransport 0x60000008d480 listenerPort=2222 publishBonjourService=0 secure=1> serverCerts=(
    "<SecIdentity 0x60000027ee00 [0x7fffca1b4730]>",
    "<cert(0x100626ee0) s: NSLogger self-signed SSL i: NSLogger self-signed SSL>"
)

**Comment by ytx0574** [comment]
Stream error occurred: stream=<__NSCFInputStream: 0x600000109480> self=<LoggerNativeTransport 0x60000008b720 listenerPort=2222 publishBonjourService=0 secure=1> error=Error  Domain  =NSOSStatusErrorDomain Code=-9801 "errSSLNegotiation: Cipher Suite negotiation failure " UserInfo={_kCFStreamErrorCodeKey=-9801, _kCFStreamErrorDomainKey=3}

**Comment by fpillet** [comment]
At this point you should disable SSL and just use unencrypted connections. I don't have a 10.13 beta installed for testing.

It looks like the OS is tightening rules as to how to connect to the desktop.

**Comment by ytx0574** [comment]
I disable SSL, But must pass code to run NSLogger client can to see the log.

**Comment by fpillet** [comment]
What do you mean by "pass code" ?

**Comment by ytx0574** [comment]
only use xcode run NSLogger Code, can see the log.     can be used in the App Store release? How to ensure the console output together?

**Comment by fpillet** [comment]
output to console in AppStore release ? I do not recommend that since you need to connect the device to Xcode to see the console when the app is running... But you should be able to use direct TCP (non-SSL) connections by properly configuring NSLogger on the client side

**Comment by ytx0574** [comment]
Yes, but I want to know to use NSLogger to App Store conference will not be refused?Because sometimes the customer bugs, I need to upload the log to our server.How do use NSLogger in xcode console output at the same time?

**Comment by fpillet** [comment]
Please read the docs and API, you can configure NSLogger to log to the console and to the network at the same time. You also have the option of logging to a file, then you can upload this file to a server of yours and later open it with the desktop NSLogger

**Comment by tjanela** [comment]
This worked for me (I'm using an NSLogger logger for CocoaLumberjack from https://github.com/0xced/XCDLumberjackNSLogger):
```swift
let nsLogger = XCDLumberjackNSLogger(bonjourServiceName: Configuration.buildUser)
var options = LoggerGetOptions(nsLogger.logger)
options &= ~(UInt32(kLoggerOption_UseSSL))
options &= ~(UInt32(kLoggerOption_BrowsePeerToPeer))
LoggerSetOptions(nsLogger.logger, options)
DDLog.add(nsLogger)
```
