### ISSUE TITLE
README snippet - Ambiguous use of 'log'

### ISSUE THREAD

**Issue by neoneye** [fpillet/NSLogger#228]
In the [readme](https://github.com/fpillet/NSLogger/blob/master/README.markdown) there is this snippet:

    fileprivate let log = Logger.shared.log
    log(.network, .error, "Oups! " + "No more paper. 🐞")

Xcode writes the error text `Ambiguous use of 'log'` followed by `Found this candidate` for each of the `Logger.shared.log` functions

Xcode 8.3.2 (8E2002)
macOS 10.12.4 Sierra

**Comment by fpillet** [comment]
Fixed with a different API
