### ISSUE TITLE
Log to Console has wrong (UTC) timezone

### ISSUE THREAD

**Issue by MeteC** [fpillet/NSLogger#232]
Hi, using log to console at the same time as NSLogger is super useful if one writes apps that need to be tested in e.g. Flight Mode or without network connection. I notice that the timezone of the write-out to the console is not localised though, seems to be stuck in UTC.

Here's a sample two lines of my output to show this (I'm in European Summer timezone), the first is logged by NSLog, the second by LoggerView(...)

`2017-07-19 12:24:54.771952+0200 DSIGN Pro[1919:648294] Setup Top Toolbar`
`10:24:54.0771      Main thread | viewWillDisappear: CollectionListController`

**Comment by MeteC** [comment]
(in the NSLogger app at the same time, the timezone (for the same message) is displayed correctly)

**Comment by fpillet** [comment]
Wow it's been a long time since you reported this issue ... but I finally fixed it! and it was a one-liner fix. Upcoming in 1.9.8, thank you for reporting!
