### ISSUE TITLE
Buffer file size

### ISSUE THREAD

**Issue by Yurssoft** [fpillet/NSLogger#237]
I'm using your logger and it's awesome!
I was wondering - do you have a possibility to divide buffer file for example for 10 MB chunks? I understand that new log will start with every app start.

**Comment by Yurssoft** [comment]
And the possibility to delete the last file if all log files > 100 MB?

**Comment by fpillet** [comment]
The API is currently very simple and doesn't have support for this. Pull requests are welcome though (but may require some API changes so let's talk about this first if you want to implement something)

**Comment by Yurssoft** [comment]
Ok, I see. What do you think about getting existing code and integrate into NSLogger? I mean to use this code just to manage all that related to files. We can add some property (or flag) to turn it on/off. This will allow people like me use new extended features, while others will use the same codebase without any change.

**Comment by Yurssoft** [comment]
Any thoughts on that?

**Comment by fpillet** [comment]
I don't understand your suggestion. Can you elaborate ?

**Comment by Yurssoft** [comment]
Ok, imagine I ship app to store and do not have a connection to the phone. I set option kLoggerOption_BufferLogsUntilConnection. That means that I will have the file with all logs until connection to the desktop app. On every app start, I will set buffer file with a unique file name. In this case, I will run app 200 times. I will have 200 different app logs. What I mean is that would be good to have a possibility to limit the maximum number of buffer files. For example, if we have limit 20 logs, on every buffer file creating we will check how much files we already have and delete the oldest file. In that way, we will have only 20 files in our system.
When to use this? When you don't have access to a device, but would like to send logs. I can attach logs to crash library and then investigate what went wrong in the desktop app. 
Can you please tell me if that is a good idea or not? I understand that your logger has little another aim.

I have already implemented thing what I am talking about:
[Here AppDelegate](https://github.com/Yurssoft/QuickFile/blob/master/QuickFile/Additional%20Classes/YSAppDelegate.swift#L123)
