### ISSUE TITLE
Swift 4 function name logging

### ISSUE THREAD

**Issue by Yurssoft** [fpillet/NSLogger#238]
As I was using NSLogger I didn't see function names in logs. As I looked up there were function names passing to logger. My question is maybe I am missing out something? I would like to see function names by default. Thanks in advance.

```
[56      ] 16:28:13.146 | Controller | Main thread | Player: something happened
```

<img width="221" alt="screen shot 2017-10-03 at 16 45 41" src="https://user-images.githubusercontent.com/7051552/31128398-55e5b172-a85a-11e7-9bd1-3432fd93db2f.png">

**Comment by fpillet** [comment]
Did you press the ƒ button at bottom of the log window?

**Comment by Yurssoft** [comment]
:) I see now. Ok, also I would like to see same function names when I am exporting to .txt file. Could you please tell me if I can export to .txt files and find function names there?

**Comment by fpillet** [comment]
I think the text export doesn't currently honor the "calling function" display parameter.

**Comment by Yurssoft** [comment]
Could you please add this in next release?
