### ISSUE TITLE
memory leak or release too slow cause app extension crash

### ISSUE THREAD

**Issue by PatrickSCLin** [fpillet/NSLogger#240]
Hi, I'm trying to use NSLogger in out project (because Xcode debugging is not work in  new broadcast upload extension for now)

I found memory was raising quickly, it takes time to release memory, sometime app extension just crash before memory be released.

Can NSLogger optimize memory limitation for app extension ?

**Comment by fpillet** [comment]
I'm not sure what you're asking for. There is an option in NSLogger, `kBufferLogsUntilConnection` that you can remove to cancel buffering. Buffering can also be done in a file instead of memory with the `LoggerSetBufferFile` function;

**Comment by PatrickSCLin** [comment]
how ?  is this correct ?
```
let options = UInt32(kLoggerOption_BrowseBonjour|kLoggerOption_BrowsePeerToPeer|kLoggerOption_BrowseOnlyLocalDomain|kLoggerOption_UseSSL|kLoggerOption_CaptureSystemConsole)

LoggerSetOptions(nil, options)
        
LoggerSetupBonjourForBuildUser()

DispatchQueue.global(qos: .default).async {
    
    while true {
        
        Log(.Custom("Leak"), .Info, "leak")
        
        usleep(1000)
        
    }
    
}
```

**Comment by fpillet** [comment]
Yes this looks correct and you won't get the logs when connecting that were emitted prior to connection

**Comment by PatrickSCLin** [comment]
I see memory usage is always raising
