### ISSUE TITLE
Remote logging

### ISSUE THREAD

**Issue by jyounus** [fpillet/NSLogger#243]
Could this be used somehow to allow remote debugging with users? I'm thinking of something along the lines of having a setting where the user can enable/disable remote logging in case they need help with an issue. Then I could see their logs on a backend.

Now my question is, can this work together with something like loggly or logz.io relatively easily? How about using the desktop viewer app to filter them by tags etc?

**Comment by fpillet** [comment]
I have, in the past, remotely logged stuff by setting the remote host (`LoggerSetViewerHost`) to point to my machine. This worked beautifully to live-debug issues.

If you want to send logs to another logging service, you'll have to write the support code to do this. Same if you want to view logs from remote services using the desktop viewer.

**Comment by jyounus** [comment]
Fair enough, that makes sense. Will look into it, thanks a lot!
