### ISSUE TITLE
Abstracting NSLogger behind a new layer

### ISSUE THREAD

**Issue by jyounus** [fpillet/NSLogger#244]
Hey there,

I'm trying to set up NSLogger in such a way, so it's easy enough for me to replace it in the future, if necessary. This means I don't want to be using NSLogger directly in each file of my project to log things.

Instead I want to create a custom class which hides NSLogger. I've done that, however I also want the correct function name/file name/line numbers to work in the desktop app. How could I "forward" that info to NSLogger?

I'm current using SwiftyBeaver for my logging lib, and I've abstracted that away as well behind a custom class. This is what I do in code:
```
func verbose(_ message: @autoclosure () -> Any, _ file: String = #file, _ function: String = #function, line: Int = #line) {
        log.verbose(message, file, function, line: line)
    }
```

This retains the original file name/function/line number where I call my custom class from when printing to the console. How could I pass these parameters to NSLogger? (I'm obviously using the Swift version of NSLogger using Cocoapods).

Thanks

**Comment by fpillet** [comment]
It's easy as you can directly call the C API from Swift instead of going through the additional NSLogger Swift wrapper that we provide. Just look at how the Swift wrapper works and use the relevant parts in your code.

**Comment by jyounus** [comment]
Ah okay, awesome! Will do, thanks!

**Comment by jyounus** [comment]
@fpillet 

When I copy most of the code of the Swift wrapper and modify it in my project, it says ```Use of unresolved identifier 'LogImage_noFormat'```. Had a quick look and it seems to be a private method that I don't have access to from my project. 

Xcode suggests ```Did you mean 'LogMessageCompat'?``` or ```Did you mean 'LogMessageToF_va'?```. Are either of these appropriate replacements? Or maybe a different public method from the LoggerClient file? https://github.com/fpillet/NSLogger/blob/a52e7b060c3d896ea24a535912168a3cb6809011/Client/iOS/LoggerClient.m#L2808

**Comment by jyounus** [comment]
I ended up using ```LogMessageRawF``` for logging messages, ```LogImageDataF``` for logging images and ```LogDataF``` for logging data. If that's incorrect, please let me know.

**Comment by fpillet** [comment]
@jyounus any call you use that produces the expected result is the right one 👍
