### ISSUE TITLE
Any update for the deprecated OSAtomicIncrement32Barrier() in iOS 10

### ISSUE THREAD

**Issue by insha** [fpillet/NSLogger#247]
Once I change my app's target deployment to iOS `10.0` and compile I get 9 errors raised by the build process about the `OSAtomicIncrement32Barrier()` being deprecated in iOS 10.0 and it is recommending to "Use atomic_fetch_add() from <stdatomic.h> instead".

My questions:

1. Is it possible to use NSLogger for an app with the deployment target set to `10.0` when building the app using Xcode 9.1?

2. Is this change in the pipeline for NSLogger?

I would submit a merge request, but my knowledge of these functions and their proper usage is weak. Therefore any help would be greatly appreciated.

macOS: 10.13.1
Xcode: 9.1

**Comment by fpillet** [comment]
Interesting, I mostly compile with iOS 9 compat still in, so I didn't see this deprecation. Annoying for people who want to keep compiling with older SDKs if we change it: thanks for the heads up, I'll handle it.

**Comment by insha** [comment]
👍

**Comment by fpillet** [comment]
Fixed, thanks to @jllubia ! Release soon.
