### ISSUE TITLE
Pod update issue

### ISSUE THREAD

**Issue by Noroxs** [fpillet/NSLogger#248]
Hello,

I'm working with NSLogger and I'm currently upgrading my project to Xcode 9. With the change of strict prototype warnings I will get an error (yes error not warning) for the `LoggerClient.h:124 extern void LoggerSetupBonjourForBuildUser() NSLOGGER_NOSTRIP;
`.

I noticed that you fixed the problem in the source code but you didn't publish the fix. Could you please publish this current master version that `pod 'NSLogger'` include this fix?

**Comment by fpillet** [comment]
Released.
