### ISSUE TITLE
I open client but nothing to show.

### ISSUE THREAD

**Issue by adsl99801** [fpillet/NSLogger#250]
Client dont show any window.

NSLogger.h version 1.8.3 8-MAY-2017
platform :ios, '11.2'
target 'XXX' do
  use_frameworks!
  pod "NSLogger"
  pod "NSLogger/Swift"
end

client:
ipod simulator 

1.31 MB NSLogger-Desktop.Viewer-v1.8.3.zip
My project is mix swift and xcode
in swift code:
 Log(.App, .Info, "add")
in object c code:
LoggerApp(1, @"Hello world! Today is: %s", "dff");

**Comment by fpillet** [comment]
Please try again with 1.9.0. Make sure you are on the same Wifi network, or that at least both your Mac and your iOS device has Wifi turned on (for Wifi P2P to work)
