### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by MaleBug** [fpillet/NSLogger#251]
Hi,
    I was planning to integrate NSLogger to my custom framework but I encountered this error during runtime: 

Undefined symbols for architecture x86_64:
  "_LoggerInit", referenced from:
      -[LogManagerTest test_NSLogger_create_log_files] in LogManagerTest.o
  "_LoggerSetBufferFile", referenced from:
      -[LogManagerTest test_NSLogger_create_log_files] in LogManagerTest.o
  "_LoggerStart", referenced from:
      -[LogManagerTest test_NSLogger_create_log_files] in LogManagerTest.o
  "_LogMessage", referenced from:
      -[LogManagerTest test_NSLogger_create_log_files] in LogManagerTest.o
  "_LogMessageF", referenced from:
      -[LogManagerTest test_NSLogger_create_log_files] in LogManagerTest.o
      -[LogManager logMessage:fileName:logLevelFlag:leadingUnmaskedMessage:] in libPersonalDataVault.a(LogManager.o)
      -[LogManager acaengineLogMessage:logLevelFlag:] in libPersonalDataVault.a(LogManager.o)
      -[LogManager logFileEncodedString:logFileName:] in libPersonalDataVault.a(LogManager.o)
  "_LoggerFlush", referenced from:
      -[LogManagerTest test_NSLogger_create_log_files] in LogManagerTest.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I installed NSLogger using CocoaPods and also linked all SystemConfiguration and CFNetwork framework as instructed in the docs.  I did not encounter this issue when I was trying out NSLogger on a new project.   Any ideas where I might have missed out something.  Would love to use this in my framework as a logging tool.

Thanks and Regards,
Pau

**Comment by fpillet** [comment]
Please try with 1.9.0, works fine here
