### ISSUE TITLE
Carthage builds both targets

### ISSUE THREAD

**Issue by c0diq** [fpillet/NSLogger#253]
There are now two targets but it's not possible to decide which one to build with Carthage. As such when carthage builds the second target (NSLoggerSwift), it seems to override the previous target NSLogger.framework output.

**Comment by c0diq** [comment]
It looks like the issue was fixed. But no release was made.

**Comment by fpillet** [comment]
Released.  I had to make two mutually exclusive frameworks for Carthage and Cocoapods to live in harmony. The `import NSLogger` statement for Carthage in the NSLogger.swift file was triggering a Cocoapods warning and preventing the release.
