### ISSUE TITLE
Plus de fonction Log avec la 1.9.0

### ISSUE THREAD

**Issue by nicoleo2014** [fpillet/NSLogger#258]
Hello,
Les Logs ne sont plus reconnus avec la nouvelle version 1.9.0

Toutes les lignes
`Log(.App, .Debug, "hello")`
Ne sont plus acceptées.

Testé avec un projet vide en Swift 4, Xcode 9.2.
NSLogger installé avec Cocoapods.
`pod 'NSLogger/Swift'`

Merci

**Comment by nicoleo2014** [comment]
Le module NSLogger est bien reconnu, mais pas la fonction Log



Nouveau : Devenez développeur mobile iOS en 2 mois <http://bit.ly/1sDEqDJ>
de formation intensive avec la 3W Academy.
*MemoFlash* : Application gratuite pour iPhone, iPad
<http://apple.co/1KdEIUP> et Android <http://bit.ly/1EbS7Lz>. Plateforme
d'apprentissage pour tous.
www.memo-flash.com <http://www.memo-flash.com/fr/home>

Toutes nos applications sont sur : www.ab-math-games.com

2018-03-12 10:22 GMT+01:00 Florent Pillet <notifications@github.com>:

**Comment by fpillet** [comment]
Ce n'est toujours pas clair. Avez-vous une erreur de compilation ? ou alors ça compile mais les logs ne sortent pas dans le viewer ?

**Comment by nicoleo2014** [comment]
Ca ne compile pas

**Comment by fpillet** [comment]
Utilisez `Logger.shared.log`, on a dû changer l'API.

**Comment by fpillet** [comment]
Pour info:
https://github.com/fpillet/NSLogger/blob/master/Client/iOS/NSLogger.swift

**Comment by nicoleo2014** [comment]
OK, merci. 
Une petite mise à jour du .README serait utile.  ;-)

**Comment by fpillet** [comment]
Oops bien vu. Je m'en occupe, merci de m'avoir prévenu.

**Comment by nicoleo2014** [comment]
Merci pour ta réactivité
