### ISSUE TITLE
carthage update --no-build --no-use-binaries --platform iOS

### ISSUE THREAD

**Issue by MKGitHub** [fpillet/NSLogger#264]
carthage update --no-build --no-use-binaries --platform iOS
*** Cloning NSLoggerSwift
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/fpillet/NSLoggerSwift.git /Users/mk/Library/Caches/org.carthage.CarthageKit/dependencies/NSLoggerSwift) failed with exit code 128:
remote: Repository not found.
fatal: repository 'https://github.com/fpillet/NSLoggerSwift.git/' not found

What just happened?

**Comment by glyuck** [comment]
It's a typo in documentation. You should write `github "fpillet/NSLogger"` in Cartfile instead of `fpillet/NSLoggerSwift`.
