### ISSUE TITLE
is it possible to cut another release?

### ISSUE THREAD

**Issue by edwardvalentini** [fpillet/NSLogger#267]
It looks like the `NSLogger.xcscheme` file that is checked into the `v1.9.0` release is incorrect for the changes that were made to that release.  It causes problems when using `NSLogger` as a git submodule because `Xcode` regenerates the correct `xcscheme` and then the submodule shows up as dirty.   
It looks like this issue has been corrected in master.   Would it be possible to do a `v1.9.1` release off master ?  Thank you.

**Comment by fpillet** [comment]
Sure sorry about that, will push a 1.9.1 this week

**Comment by merlin910** [comment]
Any chance of getting a 1.9.1 release that has Swift 4.2 compatibility?

**Comment by fpillet** [comment]
Released. Sorry for the delay.
