### ISSUE TITLE
Trouble loading from buffered file

### ISSUE THREAD

**Issue by subdigital** [fpillet/NSLogger#275]
I'm evaluating NSLogger for saving logs in production (`os_log` is great but it's really cumbersome to retrieve logs in the wild)

In a demo app I have this code:

```swift
        LoggerSetBufferFile(nil, "/Users/ben/Desktop/demo.nsloggerdata" as CFString)
        LoggerSetOptions(nil, UInt32(kLoggerOption_BufferLogsUntilConnection))
        
        Logger.shared.log(.app, .debug, "Some debug logs")
        Logger.shared.log(.app, .warning, "Some warning logs")
        
        for _ in 0...235 {
            Logger.shared.log(.service, .info, "Some info logs")
        }
```

If I close the NSLogger Mac app, I do see a file, and it grows in size, however when I try to open this file I get this error:

<img width="532" alt="screen shot 2019-01-18 at 12 14 06 pm" src="https://user-images.githubusercontent.com/59140/51404958-8e2e2800-1b1a-11e9-9d8a-d022d950b477.png">

I looked around for examples and all I've seen is code similar to the above. What am I doing wrong here?

**Comment by subdigital** [comment]
👋 @fpillet ;)

I run run off master for now, thanks for the lightning quick reply!

**Comment by subdigital** [comment]
Looks like I also needed to use `rawnsloggerdata` as the file extension as well. What's the difference?

**Comment by fpillet** [comment]
Raw files are just brutal storage of what goes over the wire (it's a binary format close to protobuf).

Saves from the desktop app are logs read from the wire, then later serialized with NSCoder. Hence the need for a separate extension :)
