### ISSUE TITLE
Visual Documentation of Interface elements?

### ISSUE THREAD

**Issue by winstondu** [fpillet/NSLogger#296]
I've searched extensively, but I can't find extensive documentation for various elements of the GUI are for the mac app.

Obviously, most elements are self-explanatory. However, I'm not exactly sure what the "+" times are supposed be (e.g. the +104ms)...
<img width="81" alt="Screen Shot 2020-08-04 at 3 53 50 PM" src="https://user-images.githubusercontent.com/8174310/89353319-fe53be80-d66a-11ea-9eba-61c9bbd2613d.png">

**Comment by fpillet** [comment]
Hi @winstondu , the + is the time delta from one log line to another. It is updated dynamically as you filter the logs, so you can get a sense of timeline for a given set of logs.
