### ISSUE TITLE
No output - Request for help

### ISSUE THREAD

**Issue by mwyld** [fpillet/NSLogger#301]
This looks great and keen to get it up and running. Although, I'm really struggling to get it to work.

I have followed the instructions, but feel I may be missing something? Could someone help me debug it?

I am using Xcode `12.2` on macOS Big Sur

I have downloaded the Desktop App and I have added the pod to my podfile

```
target 'MyApp' do
  capacitor_pods
  # Add your Pods here
  pod "NSLogger"
end
```
I have tried Real Devices running iOS 14 and Simulators on `12.4` with no luck.

I have tried adding the following snippets into the list

```<key>NSBonjourServices</key>
    <array>
        <string>_nslogger._tcp</string>
        <string>_nslogger-ssl._tcp</string>
    </array>
    <key>NSLocalNetworkUsageDescription</key>
    <string>Access to the local network for development builds</string>
```

I have tried adding `OS_ACTIVITY_MODE` set to `disable` in Environment Variables for the run schema
![image](https://user-images.githubusercontent.com/12820928/101422094-ba5d1880-38ed-11eb-889d-a92a42cce4b9.png)

Could someone point me in the right direction?

**Comment by fpillet** [comment]
@mwyld the snippet you copied is incomplete. Here is the full version:

```
<key>NSBonjourServices</key>
<array>
	<string>_nslogger._tcp</string>
	<string>_nslogger-ssl._tcp</string>
</array>
<key>NSLocalNetworkUsageDescription</key>
<string>Access to the local network for development builds</string>
```

You were missing the first `<key>` line. I think this should solve your issue.

**Comment by mwyld** [comment]
Thanks @fpillet for checking this out for me. I got excited it could have been this fix but after checking it looks like I left it off my github description. I had the key in there

**Comment by fpillet** [comment]
@mwyld ok the issue may be something else then. I don't use `OS_ACTIVITY_MODE` and it didn't cause any issue for me. On Big sur there may be some issue with capturing the local console, so try this very early when running your app (i.e. first thing in `applicationDidFinishLaunching`):

```
LoggerSetOptions(nil, (LoggerGetOptions(nil) & ~UInt32(kLoggerOption_CaptureSystemConsole)) | UInt32(kLoggerOption_BufferLogsUntilConnection))
```

This will prevent NSLogger from trying to capture the local console. Not sure it will fix your issue though.

I assume you have the desktop viewer up and running? When it's not logging, it doesn't display any window currently.

**Comment by mwyld** [comment]
I just had a quick go at adding it in (Will have a further look into it when I've got some more time available).
I build hybrid apps in the ionic framework and export it to Xcode so I don't have too much knowledge with swift/objectiveC

![image](https://user-images.githubusercontent.com/12820928/101693644-d5ed2e00-3a69-11eb-9ad1-0f2e385abfbc.png)

**Comment by fpillet** [comment]
add this line along with the other import lines:

```
import NSLogger
```

Also if the problem is capturing the local console and you do not specifically use NSLogger for logging, I don't think it will be of much use to you...

**Comment by fpillet** [comment]
@mwyld I also see that you patched the wrong function. Move the `LoggerSetOptions` call to the previous function just before `FirebaseApp.configure()`

**Comment by mwyld** [comment]
Okay, I've made those amendments and tried re-running. But it doesn't run the NSLogger.

I think I just need something easier to read than the xcode output version. When a JSON string comes through, it just becomes unreadable!

![image](https://user-images.githubusercontent.com/12820928/101694207-aab70e80-3a6a-11eb-9b88-d590b9c800a6.png)

**Comment by fpillet** [comment]
To verify that NSLogger works correctly you can add this just after `LoggerSetOptions`:

```
LogMessageRaw("Hello from NSLogger")
```

If everything works the NSLogger window will open on your Mac

**Comment by mwyld** [comment]
Ah interestingly, it still didn't come up?

Maybe I've missed a previous step. This may be a couple of dumb questions but...

- Do you need to do both Podfile and Carthage install?
- Once you add the pod line should I be doing some sort of pod refresh?

Apologies for, lack of experience with Xcode

**Comment by fpillet** [comment]
You obviously did a `pod install` otherwise your `import NSLogger` wouldn't have compiled at all, so I think you're good on this front.

You don't need to have NSLogger installed both in Podfile and Carthage -- only one is necessary. Throw away the other.

No need to apologize, build systems have become more complex and macOS / iOS more restrictive over the years, and getting NSLogger to work can be more challenging than it should be. Sorry about that.

**Comment by mwyld** [comment]
No worries. I didn't realise the confirmation for 
```
<key>NSLocalNetworkUsageDescription</key>
<string>Access to the local network for development builds</string>
```
popped up on my iPhone, after accepting this the NSLogger appeared! but looks like its not logging anything else.

Maybe it's because its a hybrid app. There could be craziness going on under the hood that bypasses the hooks this needs?

**Comment by fpillet** [comment]
Now that you have the Alert thing sorted out, you can comment out the `LoggerSetOptions` line so that NSLogger can start capturing the console again! Try it that should work now.

**Comment by mwyld** [comment]
Scrap that. I pulled the two lines we originally put in. It now works! looks like all it needed was the import!

![image](https://user-images.githubusercontent.com/12820928/101696035-611bf300-3a6d-11eb-83fd-e8e06c5b70d6.png)

**Comment by mwyld** [comment]
Wheyyy! thanks so much @fpillet ! your a legend! Maybe just an update to the README file might help others that hit the same issue?

**Comment by fpillet** [comment]
@mwyld yeah I'm a bit behind on documenting how to cope with the latest changes in the OS. Glad you got it working 👍  Enjoy !

**Comment by azav** [comment]
In Swift, you have to specifically import frameworks to make them available to your class.

**Comment by azav** [comment]
> On Dec 9, 2020, at 4:26 PM, Matt Wyld <notifications@github.com> wrote:
> 
> 
> Wheyyy! thanks so much @fpillet <https://github.com/fpillet> ! your a legend! Maybe just an update to the README file might help others that hit the same issue?
> 
It’s kind of understood that you have to do that.  It might not hurt as a reminder though.
